In [1]:
import numpy as np

In [2]:
def f1_score(precision,recall):
  try:
    return 2 * precision *recall / (precision+recall)
  except:
    return 0.0

In [3]:
precision = 0.5
recall = 0.5

f1_score(precision,recall)

0.5

In [4]:
precision = 0.1
recall = 0.9

f1_score(precision,recall)

0.18000000000000002

In [5]:
precision = 0
recall = 1

f1_score(precision,recall)

0.0

In [6]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target == 9] = 1
y[digits.target != 9] = 0

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X,y,random_state = 666)

In [8]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.9755555555555555

In [9]:
y_predict = log_reg.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_predict)

array([[403,   2],
       [  9,  36]])

In [12]:
from sklearn.metrics import precision_score

precision_score(y_test,y_predict)

0.9473684210526315

In [13]:
from sklearn.metrics import recall_score

recall_score(y_test,y_predict)

0.8

In [15]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

### Balance between precision and recall score

In [16]:
log_reg.decision_function(X_test)

array([-21.40714948, -32.89262648, -16.39243808, -79.80810383,
       -48.04348063, -24.19379484, -44.58255879, -24.27094251,
        -1.13674172, -18.99730509, -65.81476498, -50.95902762,
       -30.94556809, -45.9427346 , -37.36316146, -29.48254454,
       -36.94023003, -82.7759675 , -37.59789854,  -9.89194432,
        -9.25183011, -85.2195169 , -16.74211019, -45.35263504,
        -5.02468891, -48.26624913, -11.66903208, -37.39432792,
       -25.08560572, -13.605257  , -16.61281138, -28.78319062,
       -34.35313536, -28.5259952 ,  -8.08997035,  -4.56481781,
       -22.01939228, -21.86719657, -31.26801878, -23.3204391 ,
       -26.90095195, -62.22768164, -37.701467  , -66.36890278,
       -20.08912915, -16.71988573, -18.15215277, -21.55810078,
       -28.96997648, -19.62495591,   2.38247507,   7.74435468,
       -34.89756131, -42.70451086, -25.61129839, -34.73381845,
        -7.59905476, -49.49098432, -51.52814178,  19.6454751 ,
       -10.05349503, -31.98628164, -11.49870831,  -1.37

In [17]:
log_reg.decision_function(X_test)[:10]

array([-21.40714948, -32.89262648, -16.39243808, -79.80810383,
       -48.04348063, -24.19379484, -44.58255879, -24.27094251,
        -1.13674172, -18.99730509])

In [18]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
decision_scores = log_reg.decision_function(X_test)

In [20]:
np.min(decision_scores)

-85.70242387670395

In [21]:
np.max(decision_scores)

19.862336022298287

In [22]:
y_predict_2 = np.array(decision_scores>=5,dtype='int')

In [23]:
confusion_matrix(y_test,y_predict_2)

array([[404,   1],
       [ 21,  24]])

In [24]:
precision_score(y_test,y_predict_2)

0.96

In [25]:
recall_score(y_test,y_predict_2)

0.5333333333333333

In [27]:
y_predict_3 = np.array(decision_scores>=-5,dtype='int')

In [28]:
confusion_matrix(y_test,y_predict_3)

array([[390,  15],
       [  5,  40]])

In [29]:
precision_score(y_test,y_predict_2)

0.7272727272727273

In [30]:
recall_score(y_test,y_predict_2)

0.8888888888888888